version: '3.8'

services:
  Shorto:
    build: .
    image: Shorto:latest
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - PORT=3000
      - REDIRECT_PORT=3001
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./data/app:/app/data/app
    restart: unless-stopped
